# Generated by Django 4.1.4 on 2022-12-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.TextField(choices=[('0', 'Referencia'), ('1', 'CT'), ('2', 'PAGARE')], default='0'),
        ),
    ]
