# Generated by Django 4.1.4 on 2022-12-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cuenta_tipo_cuenta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuenta',
            new_name='CuentaC',
        ),
    ]
