# Generated by Django 4.1.4 on 2022-12-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cuentacliente_delete_cuenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuentaCliente',
        ),
    ]
